begin;

alter table public.profiles
  add column if not exists must_change_password boolean not null default false;

alter table public.clients
  add column if not exists is_demo boolean not null default false;
alter table public.projects
  add column if not exists is_demo boolean not null default false;
alter table public.invoices
  add column if not exists is_demo boolean not null default false;
alter table public.intake_submissions
  add column if not exists is_demo boolean not null default false;

alter table public.pages
  add column if not exists published_snapshot jsonb;
alter table public.services
  add column if not exists published_snapshot jsonb;
alter table public.services
  add column if not exists published_at timestamptz;

alter table public.media_assets
  add column if not exists caption text;
alter table public.media_assets
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create table if not exists public.portfolio_items (
  id uuid primary key default gen_random_uuid(),
  legacy_id text unique,
  slug text not null unique,
  title text not null,
  description text,
  category text not null default 'graphics',
  collection text,
  year integer,
  media_type text not null default 'image'
    check (media_type in ('image', 'video', 'pdf')),
  thumbnail_src text not null,
  preview_src text,
  original_url text,
  alt_text text not null default '',
  featured boolean not null default false,
  position integer not null default 0,
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  published_snapshot jsonb,
  published_at timestamptz,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.content_revisions (
  id bigint generated by default as identity primary key,
  entity_type text not null
    check (entity_type in ('page', 'service', 'portfolio')),
  entity_id uuid not null,
  revision_number integer not null,
  snapshot jsonb not null,
  published_by uuid references public.profiles(id),
  published_at timestamptz not null default timezone('utc', now()),
  unique (entity_type, entity_id, revision_number)
);

create index if not exists portfolio_items_status_position_idx
  on public.portfolio_items(status, position);
create index if not exists portfolio_items_category_idx
  on public.portfolio_items(category);
create index if not exists content_revisions_entity_idx
  on public.content_revisions(entity_type, entity_id, revision_number desc);

drop trigger if exists set_portfolio_items_updated_at on public.portfolio_items;
create trigger set_portfolio_items_updated_at
before update on public.portfolio_items
for each row execute function public.set_updated_at();

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.role is distinct from old.role
    and coalesce(auth.role(), '') <> 'service_role'
    and not public.has_role(array['owner']) then
    raise exception 'Only an owner can change account roles';
  end if;
  return new;
end;
$$;

create or replace function public.publish_cms_entity(
  target_type text,
  target_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  snapshot jsonb;
  next_revision integer;
begin
  if not public.has_role(array['owner', 'content_manager']) then
    raise exception 'Content publishing permission is required';
  end if;

  if target_type = 'page' then
    select jsonb_build_object(
      'title', title,
      'slug', slug,
      'content', content,
      'seo_title', seo_title,
      'seo_description', seo_description
    )
    into snapshot
    from public.pages
    where id = target_id;

    if snapshot is null then raise exception 'Page not found'; end if;
    update public.pages
    set published_snapshot = snapshot,
        status = 'published',
        published_at = timezone('utc', now()),
        updated_by = auth.uid()
    where id = target_id;
  elsif target_type = 'service' then
    select to_jsonb(service_row)
      - 'published_snapshot' - 'created_at' - 'updated_at' - 'published_at'
    into snapshot
    from public.services service_row
    where id = target_id;

    if snapshot is null then raise exception 'Service not found'; end if;
    update public.services
    set published_snapshot = snapshot,
        status = 'published',
        published_at = timezone('utc', now())
    where id = target_id;
  elsif target_type = 'portfolio' then
    select to_jsonb(portfolio_row)
      - 'published_snapshot' - 'created_at' - 'updated_at'
      - 'created_by' - 'updated_by' - 'published_at'
    into snapshot
    from public.portfolio_items portfolio_row
    where id = target_id;

    if snapshot is null then raise exception 'Portfolio item not found'; end if;
    update public.portfolio_items
    set published_snapshot = snapshot,
        status = 'published',
        published_at = timezone('utc', now()),
        updated_by = auth.uid()
    where id = target_id;
  else
    raise exception 'Unsupported content type';
  end if;

  select coalesce(max(revision_number), 0) + 1
  into next_revision
  from public.content_revisions
  where entity_type = target_type and entity_id = target_id;

  insert into public.content_revisions (
    entity_type, entity_id, revision_number, snapshot, published_by
  )
  values (target_type, target_id, next_revision, snapshot, auth.uid());

  return snapshot;
end;
$$;

create or replace function public.get_public_site_content()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'pages',
      coalesce((
        select jsonb_object_agg(
          page_row.slug,
          page_row.published_snapshot
        )
        from public.pages page_row
        where page_row.status = 'published'
          and page_row.published_snapshot is not null
      ), '{}'::jsonb),
    'services',
      coalesce((
        select jsonb_agg(service_row.published_snapshot order by service_row.position)
        from public.services service_row
        where service_row.status = 'published'
          and service_row.published_snapshot is not null
      ), '[]'::jsonb),
    'portfolioItems',
      coalesce((
        select jsonb_agg(
          portfolio_row.published_snapshot
          order by portfolio_row.position
        )
        from public.portfolio_items portfolio_row
        where portfolio_row.status = 'published'
          and portfolio_row.published_snapshot is not null
      ), '[]'::jsonb),
    'generatedAt', timezone('utc', now())
  );
$$;

create or replace function public.media_asset_usage(target_id uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce((
      select count(*)::integer
      from public.portfolio_items p
      join public.media_assets m on m.id = target_id
      where p.thumbnail_src = m.public_url
         or p.preview_src = m.public_url
         or p.original_url = m.public_url
    ), 0)
    +
    coalesce((
      select count(*)::integer
      from public.pages p
      join public.media_assets m on m.id = target_id
      where p.content::text like '%' || m.public_url || '%'
         or coalesce(p.published_snapshot::text, '') like '%' || m.public_url || '%'
    ), 0);
$$;

revoke all on function public.publish_cms_entity(text, uuid) from public;
grant execute on function public.publish_cms_entity(text, uuid) to authenticated;
revoke all on function public.get_public_site_content() from public;
grant execute on function public.get_public_site_content() to anon, authenticated;
revoke all on function public.media_asset_usage(uuid) from public;
grant execute on function public.media_asset_usage(uuid) to authenticated;

alter table public.portfolio_items enable row level security;
alter table public.content_revisions enable row level security;

drop policy if exists "published pages are public" on public.pages;
drop policy if exists "published services are public" on public.services;
revoke select on public.pages, public.services from anon;

create policy "content roles read portfolio" on public.portfolio_items
for select using (public.has_role(array['owner', 'content_manager']));
create policy "content roles manage portfolio" on public.portfolio_items
for all using (public.has_role(array['owner', 'content_manager']))
with check (public.has_role(array['owner', 'content_manager']));

create policy "content roles read revisions" on public.content_revisions
for select using (public.has_role(array['owner', 'content_manager']));

grant select, insert, update, delete on public.portfolio_items to authenticated;
grant select on public.content_revisions to authenticated;
grant usage, select on sequence public.content_revisions_id_seq to authenticated;

insert into public.pages (slug, title, status, content, published_snapshot)
values
  (
    'global',
    'Global content',
    'published',
    '{
      "site":{"brand_name":"Olympus Studio","whatsapp":"+234 808 717 2313","whatsapp_number":"2348087172313","email":"","location":"","footer_intro":"A creative studio for film, photography, campaign graphics, editorial publications, motion design, event coverage, and website development.","instagram":"","tiktok":"","x":"","linkedin":""},
      "team":[],
      "testimonials":[],
      "faqs":[],
      "partners":[]
    }'::jsonb,
    jsonb_build_object(
      'title', 'Global content',
      'slug', 'global',
      'content', '{
        "site":{"brand_name":"Olympus Studio","whatsapp":"+234 808 717 2313","whatsapp_number":"2348087172313","email":"","location":"","footer_intro":"A creative studio for film, photography, campaign graphics, editorial publications, motion design, event coverage, and website development.","instagram":"","tiktok":"","x":"","linkedin":""},
        "team":[],
        "testimonials":[],
        "faqs":[],
        "partners":[]
      }'::jsonb,
      'seo_title', null,
      'seo_description', null
    )
  ),
  (
    'portfolio',
    'Portfolio',
    'published',
    '{"header":{"eyebrow":"Selected work","title":"Portfolio","body":"Film, photography, design, editorial, and motion work from Olympus Studio."}}'::jsonb,
    jsonb_build_object(
      'title', 'Portfolio',
      'slug', 'portfolio',
      'content', '{"header":{"eyebrow":"Selected work","title":"Portfolio","body":"Film, photography, design, editorial, and motion work from Olympus Studio."}}'::jsonb,
      'seo_title', null,
      'seo_description', null
    )
  ),
  (
    'book',
    'Book a session',
    'published',
    '{"header":{"eyebrow":"Start a project","title":"Book a session","body":"Tell us what you are building and we will shape the right production approach."}}'::jsonb,
    jsonb_build_object(
      'title', 'Book a session',
      'slug', 'book',
      'content', '{"header":{"eyebrow":"Start a project","title":"Book a session","body":"Tell us what you are building and we will shape the right production approach."}}'::jsonb,
      'seo_title', null,
      'seo_description', null
    )
  )
on conflict (slug) do nothing;

update public.pages
set published_snapshot = jsonb_build_object(
      'title', title,
      'slug', slug,
      'content', content,
      'seo_title', seo_title,
      'seo_description', seo_description
    ),
    status = 'published',
    published_at = coalesce(published_at, timezone('utc', now()))
where published_snapshot is null;

update public.services as service_row
set published_snapshot = to_jsonb(service_row)
      - 'published_snapshot' - 'created_at' - 'updated_at' - 'published_at',
    status = case when status = 'archived' then status else 'published' end,
    published_at = case
      when status = 'archived' then published_at
      else coalesce(published_at, timezone('utc', now()))
    end
where published_snapshot is null;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'site-media',
  'site-media',
  true,
  104857600,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml',
    'application/pdf', 'video/mp4', 'video/webm'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Curated demo records keep the initial operations screens populated.
insert into public.clients (id, name, email, company, notes, is_demo)
values
  ('10000000-0000-0000-0000-000000000001', 'Amara Okoye', 'amara@example.com', 'Northstar Conference', 'Demo client for the initial workspace.', true),
  ('10000000-0000-0000-0000-000000000002', 'David Mensah', 'david@example.com', 'Meridian House', 'Demo client for the initial workspace.', true)
on conflict (id) do nothing;

insert into public.projects (
  id, client_id, title, code, description, service, budget, currency,
  start_date, due_date, status, is_demo
)
values
  ('20000000-0000-0000-0000-000000000001', '10000000-0000-0000-0000-000000000001', 'Northstar Summit 2026', 'DEMO-001', 'Conference film, photography, and highlight delivery.', 'Events & Conferences', 1850000, 'NGN', current_date - 14, current_date + 24, 'active', true),
  ('20000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000002', 'Meridian Brand Refresh', 'DEMO-002', 'Campaign identity and launch assets.', 'Graphics & Branding', 950000, 'NGN', current_date - 30, current_date + 10, 'active', true),
  ('20000000-0000-0000-0000-000000000003', '10000000-0000-0000-0000-000000000001', 'Annual Report Film', 'DEMO-003', 'Short documentary and editorial stills.', 'Photography & Film', 720000, 'NGN', current_date, current_date + 45, 'draft', true)
on conflict (id) do nothing;

insert into public.milestones (
  id, project_id, title, description, due_date, position, status
)
values
  ('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'Creative direction', 'Approve the visual treatment and interview plan.', current_date + 3, 0, 'awaiting_approval'),
  ('30000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001', 'Event production', 'Capture the conference and green carpet interviews.', current_date + 14, 1, 'in_progress'),
  ('30000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000002', 'Campaign system', 'Deliver the core identity and launch templates.', current_date + 7, 0, 'in_progress')
on conflict (id) do nothing;

insert into public.invoices (
  id, project_id, invoice_number, status, currency, subtotal, tax,
  due_date, issued_at, paid_at, payment_reference, notes, is_demo
)
values
  ('40000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'DEMO-INV-001', 'open', 'NGN', 925000, 0, current_date + 7, timezone('utc', now()), null, null, 'Demo 50% production deposit.', true),
  ('40000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000002', 'DEMO-INV-002', 'paid', 'NGN', 950000, 0, current_date - 5, timezone('utc', now()) - interval '14 days', timezone('utc', now()) - interval '6 days', 'BANK-DEMO-002', 'Demo paid campaign invoice.', true),
  ('40000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000003', 'DEMO-INV-003', 'draft', 'NGN', 360000, 0, current_date + 21, null, null, null, 'Demo draft deposit.', true)
on conflict (id) do nothing;

insert into public.intake_submissions (
  id, kind, name, email, title, service, budget, timeline, message, status, is_demo
)
values
  ('50000000-0000-0000-0000-000000000001', 'project', 'Ife Adebayo', 'ife@example.com', 'Product launch film', 'Photography & Film', '₦1m–₦2m', 'Next month', 'We need a launch film and campaign stills.', 'new', true),
  ('50000000-0000-0000-0000-000000000002', 'event', 'Zainab Bello', 'zainab@example.com', 'Leadership retreat', 'Events & Conferences', '₦500k–₦1m', 'Six weeks', 'Two-day event coverage with a highlight film.', 'reviewing', true)
on conflict (id) do nothing;

commit;
